jokes:
  - "Why don't skeletons fight each other? They don't have the guts!"
  - "Why did the Creeper cross the road? To blow up the chicken!"
  - "Knock knock. Who’s there? Cow says. Cow says who? No silly, cow says moo!"
  - "What do you call a Minecraft bed? A block of comfort!"
  - "Why did the chicken join Minecraft? To lay eggs in the game world!"

cooldown-seconds: 10